# Generated by Django 3.1.7 on 2021-03-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userfollower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollower',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.user'),
        ),
    ]
