# Generated by Django 3.1.7 on 2021-03-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'verbose_name_plural': 'Tweets'},
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('tweet', models.ManyToManyField(to='tweets.Tweets')),
            ],
        ),
    ]
